spring.application.name=ws-ms-detectionAnomalie
server.port=8082
api.base.url=https://admin.detection.tn/api/hotel


#BD
# create and drop tables and sequences, loads import.sql
spring.jpa.hibernate.ddl-auto=none
# Oracle settings
spring.datasource.url=jdbc:oracle:thin:@51.210.222.180:1521:XE
#spring.datasource.url=jdbc:oracle:thin:@51.210.222.180:1521:xe

spring.datasource.username=newtresor
spring.datasource.password=newtresor
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true